### ISSUE TITLE
Gives this error when trying to enable plugin

### ISSUE THREAD

**Issue by Tivantri** [Sage-of-Mirrors/RedDeadBlend2#8]
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\blender-3.2.0-windows-x64\blender-3.2.0-windows-x64\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RedDeadBlend2\__init__.py", line 24, in <module>
    from .importing import ImportYdr, ImportYdd, ImportYft
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RedDeadBlend2\importing.py", line 10, in <module>
    from . import pylibdrawable
ImportError: DLL load failed while importing pylibdrawable: The specified module could not be found.

**Comment by Lapua1** [comment]
same issue man hope they fix it.
